-- Tipos (Enums)
DO $$ BEGIN
    CREATE TYPE categoria_carta AS ENUM ('Común', 'Raro', 'Épico', 'Legendario');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE tipo_mision AS ENUM ('Fácil', 'Media', 'Difícil', 'Extrema');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Tabla: perfil
CREATE TABLE IF NOT EXISTS perfil (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre text NOT NULL,
  email text,
  contrasena text,
  f_nac date,
  creado_en timestamptz DEFAULT now()
);

-- Tabla: mision
CREATE TABLE IF NOT EXISTS mision (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo tipo_mision NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  recompensa categoria_carta NOT NULL
);

-- Tabla: carta
CREATE TABLE IF NOT EXISTS carta (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre_carta text,
  categoria categoria_carta NOT NULL,
  borde text,
  imagen text,
  centro text,
  normal_map text,
  texto varchar(255),
  propietario int REFERENCES perfil(id) ON DELETE SET NULL,
  creada_en timestamptz DEFAULT now()
);

-- Tabla: progreso_usuario
CREATE TABLE IF NOT EXISTS progreso_usuario (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  perfil_id int REFERENCES perfil(id) ON DELETE CASCADE,
  mision_id int REFERENCES mision(id) ON DELETE CASCADE,
  completado boolean DEFAULT false,
  fecha date DEFAULT current_date
);

-- Función para misiones aleatorias
CREATE OR REPLACE FUNCTION get_daily_missions(limit_count int DEFAULT 3)
RETURNS SETOF mision AS $$
BEGIN
  RETURN QUERY SELECT * FROM mision ORDER BY random() LIMIT limit_count;
END;
$$ LANGUAGE plpgsql;

-----------------------------------------
-- SEEDERS (Datos Iniciales)
-----------------------------------------

-- Limpiar tablas
TRUNCATE TABLE progreso_usuario CASCADE;
TRUNCATE TABLE carta CASCADE;
TRUNCATE TABLE mision CASCADE;
TRUNCATE TABLE perfil CASCADE;

-- 1. Perfil de prueba (id = 1)
INSERT INTO perfil (id, nombre, email, contrasena, f_nac) 
VALUES (1, 'JorgeKirko47', 'jorge@example.com', '123456', '1995-05-15');

-- 2. Cartas de prueba
INSERT INTO carta (id, nombre_carta, categoria, borde, imagen, centro, normal_map, texto, propietario) VALUES 
(1, 'Kirko Básico', 'Común', 'default', 'pokmeon.png', 'buffkirk.jpeg', 'paper1.jpg', 'La forma básica y trabajadora de Kirko.', 1),
(2, 'Kirko Entrenador', 'Raro', 'silver', 'pokmeon.png', 'buffkirk.jpeg', 'paper1.jpg', 'Levantando 200kg sin sudar.', 1),
(3, 'Mewtwo Cósmico', 'Épico', 'gold', 'pokmeon.png', 'pokmeon.png', 'paper1.jpg', 'Un ente cósmico incomparable.', NULL),
(4, 'Kirko Dorado', 'Legendario', 'diamond', 'pokmeon.png', 'buffkirk.jpeg', 'paper1.jpg', 'El pináculo del esfuerzo físico.', NULL);

-- 3. Misiones verificables (30 misiones)
INSERT INTO mision (id, tipo, nombre, descripcion, recompensa) VALUES 
(1, 'Fácil', 'Caminar 2,000 pasos', 'Usa tu podómetro para registrar 2,000 pasos hoy.', 'Común'),
(2, 'Media', 'Caminar 5,000 pasos', 'Llega a 5,000 pasos verificados por la app.', 'Raro'),
(3, 'Difícil', 'Caminar 10,000 pasos', 'Alcanza la meta de 10,000 pasos diarios.', 'Épico'),
(4, 'Fácil', 'Tomar una foto al aire libre', 'Usa la cámara para capturar una foto con mucha luz natural.', 'Común'),
(5, 'Media', 'Leer un texto en voz alta', 'Usa el micrófono y lee el texto mostrado en pantalla sin errores.', 'Raro'),
(6, 'Fácil', 'Diario de 50 palabras', 'Escribe cómo te sientes usando el teclado (mínimo 50 palabras).', 'Común'),
(7, 'Difícil', 'Visitar un parque', 'La app verificará mediante GPS que te encuentras en un área verde.', 'Épico'),
(8, 'Media', 'Agitar el teléfono', 'Agita el teléfono 50 veces seguidas. Usa tu giroscopio.', 'Raro'),
(9, 'Fácil', 'Trivia rápida', 'Responde 3 preguntas de conocimiento general en menos de 1 minuto.', 'Común'),
(10, 'Media', 'Desconexión boca abajo', 'Mantén el teléfono boca abajo sobre la mesa durante 30 minutos.', 'Raro'),
(11, 'Difícil', 'Completar el puzzle', 'Resuelve el rompecabezas en pantalla en menos de 2 minutos.', 'Épico'),
(12, 'Fácil', 'Cantar por 10s', 'Graba un audio cantando o tarareando una canción por 10 segundos.', 'Común'),
(13, 'Media', 'Caza de colores', 'Usa la cámara y apunta hacia algo de color azul brillante.', 'Raro'),
(14, 'Difícil', 'Correr 2 km', 'Corre 2 kilómetros seguidos usando el podómetro y GPS para verificar velocidad.', 'Épico'),
(15, 'Fácil', 'Escanear un QR', 'Encuentra y escanea un código QR usando tu cámara.', 'Común'),
(16, 'Media', 'Subir 3 pisos', 'Sube 3 pisos por escalera. Se verificará con el barómetro/altímetro.', 'Raro'),
(17, 'Fácil', 'Dibujo en pantalla', 'Traza el patrón solicitado sin levantar el dedo.', 'Común'),
(18, 'Difícil', 'Estatua por 5 mins', 'Quédate en un lugar sin mover el celular ni caminar por 5 minutos.', 'Épico'),
(19, 'Extrema', 'Club de las 5 AM', 'Abre la app a las 5:00 AM exactas.', 'Legendario'),
(20, 'Fácil', 'Día de lluvia', 'Graba 10 segundos del sonido de la lluvia (se usa micrófono).', 'Común'),
(21, 'Media', 'Resistencia dactilar', 'Mantén presionado el botón central de la pantalla durante 60 segundos.', 'Raro'),
(22, 'Difícil', 'Rotación 360', 'Da 10 vueltas sobre ti mismo. El giroscopio contará las rotaciones.', 'Épico'),
(23, 'Media', 'Caminata rápida', 'Camina a una velocidad de al menos 5 km/h durante 10 minutos.', 'Raro'),
(24, 'Fácil', 'Encender linterna', 'Mantén la linterna encendida desde la app por 1 minuto.', 'Común'),
(25, 'Media', 'Reconocimiento facial', 'Sonríe a la cámara frontal hasta que la IA lo detecte.', 'Raro'),
(26, 'Difícil', 'Prueba matemática', 'Resuelve 5 ecuaciones matemáticas en menos de 30 segundos.', 'Épico'),
(27, 'Extrema', 'Velocidad de tipeo', 'Toca la pantalla 100 veces en solo 10 segundos.', 'Legendario'),
(28, 'Difícil', 'Llegar al gimnasio', 'Ve a un gimnasio cercano (verificación por GPS).', 'Épico'),
(29, 'Media', 'Abecedario inverso', 'Escribe Z, Y, X... hasta la A en menos de 20s en el teclado.', 'Raro'),
(30, 'Extrema', 'Maratón de pasos', 'Da 20,000 pasos en un solo día.', 'Legendario');

-- Reset sequences just in case for new inserts
SELECT setval('perfil_id_seq', (SELECT MAX(id) FROM perfil));
SELECT setval('carta_id_seq', (SELECT MAX(id) FROM carta));
SELECT setval('mision_id_seq', (SELECT MAX(id) FROM mision));
