-----------------------------------------
-- 1. LIMPIEZA DE TABLAS Y TIPOS PREVIOS
-----------------------------------------
DROP TABLE IF EXISTS progreso_usuario CASCADE;
DROP TABLE IF EXISTS carta CASCADE;
DROP TABLE IF EXISTS mision CASCADE;
DROP TABLE IF EXISTS perfil CASCADE;
DROP TABLE IF EXISTS texto_educativo CASCADE;
DROP TABLE IF EXISTS trivia_utec CASCADE;

DROP TYPE IF EXISTS categoria_carta CASCADE;
DROP TYPE IF EXISTS tipo_mision CASCADE;

-----------------------------------------
-- 2. CREACIÓN DE TIPOS (Enums limpios)
-----------------------------------------
CREATE TYPE categoria_carta AS ENUM ('Comun', 'Raro', 'Epico', 'Legendario');
CREATE TYPE tipo_mision AS ENUM ('Fácil', 'Media', 'Difícil', 'Extrema');

-----------------------------------------
-- 3. CREACIÓN DE TABLAS
-----------------------------------------

-- Tabla: perfil
CREATE TABLE perfil (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre text NOT NULL,
  email text,
  contrasena text,
  f_nac date,
  imagen_perfil text,
  creado_en timestamptz DEFAULT now()
);

-- Tabla: mision
CREATE TABLE mision (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo tipo_mision NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  recompensa categoria_carta NOT NULL
);

-- Tabla: carta
CREATE TABLE carta (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre_carta text,
  categoria categoria_carta NOT NULL,
  borde text,
  imagen text,
  centro text,
  normal_map text,
  texto varchar(255),
  propietario int REFERENCES perfil(id) ON DELETE SET NULL,
  creada_en timestamptz DEFAULT now()
);

-- Tabla: texto_educativo
CREATE TABLE texto_educativo (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contenido text NOT NULL
);

-- Tabla: trivia_utec
CREATE TABLE trivia_utec (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pregunta text NOT NULL,
  opcion1 text NOT NULL,
  opcion2 text NOT NULL,
  opcion3 text NOT NULL,
  opcion4 text NOT NULL,
  respuesta_correcta int NOT NULL CHECK (respuesta_correcta BETWEEN 1 AND 4)
);

-- Tabla: progreso_usuario
CREATE TABLE progreso_usuario (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  perfil_id int REFERENCES perfil(id) ON DELETE CASCADE,
  mision_id int REFERENCES mision(id) ON DELETE CASCADE,
  completado boolean DEFAULT false,
  fallado boolean DEFAULT false,
  fecha date DEFAULT current_date
);

-----------------------------------------
-- 4. POLÍTICAS DE SEGURIDAD (RLS)
-----------------------------------------
-- Habilitamos RLS
ALTER TABLE perfil ENABLE ROW LEVEL SECURITY;
ALTER TABLE mision ENABLE ROW LEVEL SECURITY;
ALTER TABLE carta ENABLE ROW LEVEL SECURITY;
ALTER TABLE progreso_usuario ENABLE ROW LEVEL SECURITY;

-- Permitimos lectura a cualquier usuario (incluso anónimo)
DROP POLICY IF EXISTS "Permitir lectura publica perfil" ON perfil;
CREATE POLICY "Permitir lectura publica perfil" ON perfil FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica mision" ON mision;
CREATE POLICY "Permitir lectura publica mision" ON mision FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica carta" ON carta;
CREATE POLICY "Permitir lectura publica carta" ON carta FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica progreso" ON progreso_usuario;
CREATE POLICY "Permitir lectura publica progreso" ON progreso_usuario FOR SELECT USING (true);

-- Permitimos lectura a la tabla texto_educativo
ALTER TABLE texto_educativo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica texto_educativo" ON texto_educativo;
CREATE POLICY "Permitir lectura publica texto_educativo" ON texto_educativo FOR SELECT USING (true);

-- Permitimos lectura a la tabla trivia_utec
ALTER TABLE trivia_utec ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica trivia_utec" ON trivia_utec;
CREATE POLICY "Permitir lectura publica trivia_utec" ON trivia_utec FOR SELECT USING (true);

-- Permitimos inserción publica a la tabla carta (necesario para el PackOpenerModal)
DROP POLICY IF EXISTS "Permitir insercion publica carta" ON carta;
CREATE POLICY "Permitir insercion publica carta" ON carta 
FOR INSERT 
WITH CHECK (true);

-- 1. Permitir que cualquiera (o la función pública) pueda insertar registros de progreso
DROP POLICY IF EXISTS "Permitir insercion publica progreso" ON progreso_usuario;
CREATE POLICY "Permitir insercion publica progreso" ON progreso_usuario 
FOR INSERT 
WITH CHECK (true);

-- 2. (Opcional pero recomendado) De una vez permite la actualización para cuando completen misiones
DROP POLICY IF EXISTS "Permitir update publico progreso" ON progreso_usuario;
CREATE POLICY "Permitir update publico progreso" ON progreso_usuario 
FOR UPDATE 
USING (true);
-----------------------------------------
-- 5. FUNCIONES
-----------------------------------------
CREATE OR REPLACE FUNCTION get_daily_missions(p_perfil_id int, limit_count int DEFAULT 3)
RETURNS SETOF mision AS $$
DECLARE
    v_conteo int;
BEGIN
    -- 1. Contar cuántas misiones tiene asignadas el usuario HOY
    SELECT COUNT(*) INTO v_conteo 
    FROM progreso_usuario 
    WHERE perfil_id = p_perfil_id AND fecha = CURRENT_DATE;

    -- 2. Si no tiene misiones asignadas hoy, elegimos 3 al azar y las congelamos
    IF v_conteo = 0 THEN
        INSERT INTO progreso_usuario (perfil_id, mision_id, completado, fallado, fecha)
        SELECT p_perfil_id, id, false, false, CURRENT_DATE
        FROM mision
        ORDER BY random()
        LIMIT limit_count;
    END IF;

    -- 3. Devolver las misiones que quedaron asociadas al usuario para el día de hoy
    RETURN QUERY 
    SELECT m.* FROM mision m
    JOIN progreso_usuario p ON p.mision_id = m.id
    WHERE p.perfil_id = p_perfil_id AND p.fecha = CURRENT_DATE AND p.completado = FALSE AND p.fallado = FALSE;
END;
$$ LANGUAGE plpgsql;

-----------------------------------------
-- 6. SEEDERS (Datos Iniciales Nuevos)
-----------------------------------------

-- 1. Perfil de prueba (id = 1)
INSERT INTO perfil (id, nombre, email, contrasena, f_nac) 
VALUES (1, 'JorgeKirko47', 'jorge@example.com', '123456', '1995-05-15');

-- 2. Cartas de prueba (Nuevas cartas añadidas)
INSERT INTO carta (id, nombre_carta, categoria, borde, imagen, centro, normal_map, texto, propietario) VALUES 
(1, 'Kirko Básico', 'Comun', 'default', 'pokmeon.png', 'buffkirk.jpeg', 'paper1.jpg', 'La forma básica y trabajadora de Kirko.', 1),
(2, 'Bob Esponja', 'Comun', 'default', 'pokmeon.png', 'bob.jpg', 'paper1.jpg', '¿Quién vive en la piña debajo del mar?', 1),
(3, 'Guerrero Común', 'Comun', 'silver', 'pokmeon.png', '6_1x1.jpg', 'paper1.jpg', 'Un guerrero listo para cualquier combate básico.', NULL),
(4, 'Campeón Raro', 'Raro', 'silver', 'pokmeon.png', '7_1x1.jpg', 'paper1.jpg', 'Habilidades afinadas y listas para la batalla.', NULL),
(5, 'Místico Épico', 'Epico', 'gold', 'pokmeon.png', '8_1x1.jpg', 'paper1.jpg', 'Una presencia majestuosa de poder inconmensurable.', NULL),
(6, 'Ancestral Legendario', 'Legendario', 'diamond', 'pokmeon.png', '9_1x1.jpg', 'paper1.jpg', 'Una fuerza cósmica que trasciende el tiempo.', NULL),
(7, 'Artefacto Dorado', 'Legendario', 'diamond', 'pokmeon.png', 'image3.png', 'paper1.jpg', 'Un objeto legendario envuelto en misterio.', NULL);

-- 3. Misiones (Limpias y renumeradas)
INSERT INTO mision (id, tipo, nombre, descripcion, recompensa) VALUES 
(1, 'Fácil', 'No Mover el dispositivo', 'No muevas el dispositivo durante el tiempo restante del cronometro (1 minuto).', 'Comun'),
(2, 'Fácil', 'Lectura de un texto educativo', 'Lee un texto educativo por al menos 1 minuto.', 'Comun'),
(5, 'Difícil', 'No mover el dispositivo', 'No muevas el dispositivo durante 10 minutos.', 'Epico'),
(6, 'Media', 'Lectura completa', 'Lee por 10 minutos un texto educativo completo.', 'Epico'),
(7, 'Media', 'Trivia UTEC', 'Responde 3 preguntas sobre la UTEC sin equivocarte.', 'Raro');

-- 4. Textos educativos de prueba
-- 4. Textos educativos de prueba (Largos)
INSERT INTO texto_educativo (contenido) VALUES 
('El Sol es una estrella de tipo-G de la secuencia principal y comprende aproximadamente el 99,86% de la masa del sistema solar. A diferencia de un planeta sólido, el Sol es una gigantesca bola de gas y plasma supercaliente en cuyo núcleo ocurren constantes reacciones de fusión nuclear. Estas reacciones convierten hidrógeno en helio, liberando una cantidad inmensa de energía en forma de luz y calor. Sin esta energía continua, la Tierra sería un mundo helado y oscuro, incapaz de albergar las múltiples formas de vida que conocemos hoy en día. Se estima que el Sol tiene suficiente hidrógeno para continuar este proceso durante unos 5.000 millones de años más, momento en el que comenzará su etapa de gigante roja, expandiéndose y absorbiendo a los planetas interiores como Mercurio y Venus.'),
('El cerebro humano produce suficiente electricidad para encender un foco pequeño de forma continua. Cada vez que pensamos, soñamos, vemos algo, o nos movemos, pequeñas señales eléctricas recorren los miles de millones de neuronas que conforman nuestro sistema nervioso central. Para poner esto en perspectiva, nuestro cerebro contiene más conexiones neuronales que la cantidad de estrellas estimadas en la Vía Láctea. A pesar de representar solo el 2% de nuestro peso corporal total, este fascinante órgano consume alrededor del 20% de toda la energía del cuerpo humano, incluso cuando estamos en reposo. Su plasticidad es asombrosa, permitiéndole crear nuevas rutas neuronales, aprender de la experiencia, adaptarse tras sufrir ciertos daños e incluso reorganizarse luego de una lesión cerebral traumática.'),
('La Gran Muralla China no es una única pared continua, sino una enorme red de murallas interconectadas construidas a lo largo de diversas dinastías a lo largo de siglos. Su objetivo principal era proteger el Imperio Chino de las incursiones y las invasiones nómadas provenientes del norte. Es tan larga que requeriría aproximadamente 18 meses caminarla por completo de extremo a extremo sin descansar. Aunque existe el popular mito moderno de que es visible desde el espacio a simple vista, astronautas y agencias espaciales han desmentido este hecho; desde la órbita terrestre baja, los materiales de construcción se confunden casi por completo con su entorno natural, requiriendo cámaras con lentes y equipo especial para distinguirla claramente entre las cadenas montañosas donde está emplazada.'),
('Los pulpos son criaturas verdaderamente alienígenas dentro de nuestro propio planeta azul, y tienen tres corazones: dos bombean sangre a las branquias para su oxigenación, mientras que el tercer corazón bombea la sangre oxigenada al resto del cuerpo y se detiene cuando la criatura nada, lo que explica por qué prefieren arrastrarse por el lecho marino para no agotarse. Su inteligencia los sitúa como los invertebrados más astutos, siendo capaces de resolver complejos rompecabezas, abrir tarros de rosca para obtener alimento y aprender comportamientos por simple observación. Además, poseen la fascinante habilidad de modificar rápidamente la textura y el color de su piel para camuflarse perfectamente con su entorno en fracción de segundos, engañando a posibles depredadores o acechando a sus presas sin ser detectados.'),
('Las abejas, pequeños insectos imprescindibles para la vida en la Tierra, pueden reconocer rostros humanos. Aunque pueda parecer de ciencia ficción, diversos experimentos científicos han demostrado que las abejas procesan las distintas partes del rostro humano de manera muy similar a como lo hacemos nosotros: juntando todas las piezas individuales (ojos, nariz, boca) para formar un único patrón coherente reconocible. Ellas son responsables de la polinización de una enorme porción de los alimentos de origen vegetal que consumimos diariamente. Viven en sociedades complejas dirigidas por una única abeja reina, y para comunicarse entre ellas sobre la ubicación exacta de las flores, las abejas obreras ejecutan un intrincado y preciso "baile" vibratorio en forma de ocho que transmite tanto la dirección relativa al sol como la distancia al recurso floral.');

-- 5. Trivia UTEC
INSERT INTO trivia_utec (pregunta, opcion1, opcion2, opcion3, opcion4, respuesta_correcta) VALUES 
('¿Cuál es la mejor materia?', 'Java', 'Android', 'PHP', 'COE', 2),
('¿Cuanta calificacion merece este proyecto?', '100/100', '70/100', '0/100', '50/100', 1),
('¿Quien es más grande?', 'Nacional', 'Peñarol', 'Rampla', 'Montevideo City Torque', 1),
('¿Muslera atajo bien el mundial?', 'Obvio', 'Si', 'Por supuesto', 'No', 4);
-----------------------------------------
-- 7. REINICIO DE SECUENCIAS
-----------------------------------------
SELECT setval('perfil_id_seq', (SELECT MAX(id) FROM perfil));
SELECT setval('mision_id_seq', (SELECT MAX(id) FROM mision));
SELECT setval('carta_id_seq', (SELECT MAX(id) FROM carta));
SELECT setval('texto_educativo_id_seq', (SELECT MAX(id) FROM texto_educativo));
SELECT setval('trivia_utec_id_seq', (SELECT MAX(id) FROM trivia_utec));

-----------------------------------------
-- 8. RECARGAR CACHÉ DE SUPABASE API
-----------------------------------------
-- Esto fuerza a PostgREST a recargar el esquema para que la app pueda ver las nuevas tablas
NOTIFY pgrst, 'reload schema';