-----------------------------------------
-- 1. LIMPIEZA DE TABLAS Y TIPOS PREVIOS
-----------------------------------------
DROP TABLE IF EXISTS progreso_usuario CASCADE;
DROP TABLE IF EXISTS carta CASCADE;
DROP TABLE IF EXISTS mision CASCADE;
DROP TABLE IF EXISTS perfil CASCADE;

DROP TYPE IF EXISTS categoria_carta CASCADE;
DROP TYPE IF EXISTS tipo_mision CASCADE;

-----------------------------------------
-- 2. CREACIÓN DE TIPOS (Enums limpios)
-----------------------------------------
CREATE TYPE categoria_carta AS ENUM ('Comun', 'Raro', 'Epico', 'Legendario');
CREATE TYPE tipo_mision AS ENUM ('Fácil', 'Media', 'Difícil', 'Extrema');

-----------------------------------------
-- 3. CREACIÓN DE TABLAS
-----------------------------------------

-- Tabla: perfil
CREATE TABLE perfil (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre text NOT NULL,
  email text,
  contrasena text,
  f_nac date,
  creado_en timestamptz DEFAULT now()
);

-- Tabla: mision
CREATE TABLE mision (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo tipo_mision NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  recompensa categoria_carta NOT NULL
);

-- Tabla: carta
CREATE TABLE carta (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre_carta text,
  categoria categoria_carta NOT NULL,
  borde text,
  imagen text,
  centro text,
  normal_map text,
  texto varchar(255),
  propietario int REFERENCES perfil(id) ON DELETE SET NULL,
  creada_en timestamptz DEFAULT now()
);

-- Tabla: progreso_usuario
CREATE TABLE progreso_usuario (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  perfil_id int REFERENCES perfil(id) ON DELETE CASCADE,
  mision_id int REFERENCES mision(id) ON DELETE CASCADE,
  completado boolean DEFAULT false,
  fecha date DEFAULT current_date
);

-----------------------------------------
-- 4. POLÍTICAS DE SEGURIDAD (RLS)
-----------------------------------------
-- Habilitamos RLS
ALTER TABLE perfil ENABLE ROW LEVEL SECURITY;
ALTER TABLE mision ENABLE ROW LEVEL SECURITY;
ALTER TABLE carta ENABLE ROW LEVEL SECURITY;
ALTER TABLE progreso_usuario ENABLE ROW LEVEL SECURITY;

-- Permitimos lectura a cualquier usuario (incluso anónimo)
DROP POLICY IF EXISTS "Permitir lectura publica perfil" ON perfil;
CREATE POLICY "Permitir lectura publica perfil" ON perfil FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica mision" ON mision;
CREATE POLICY "Permitir lectura publica mision" ON mision FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica carta" ON carta;
CREATE POLICY "Permitir lectura publica carta" ON carta FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura publica progreso" ON progreso_usuario;
CREATE POLICY "Permitir lectura publica progreso" ON progreso_usuario FOR SELECT USING (true);

-- 1. Permitir que cualquiera (o la función pública) pueda insertar registros de progreso
DROP POLICY IF EXISTS "Permitir insercion publica progreso" ON progreso_usuario;
CREATE POLICY "Permitir insercion publica progreso" ON progreso_usuario 
FOR INSERT 
WITH CHECK (true);

-- 2. (Opcional pero recomendado) De una vez permite la actualización para cuando completen misiones
DROP POLICY IF EXISTS "Permitir update publico progreso" ON progreso_usuario;
CREATE POLICY "Permitir update publico progreso" ON progreso_usuario 
FOR UPDATE 
USING (true);
-----------------------------------------
-- 5. FUNCIONES
-----------------------------------------
CREATE OR REPLACE FUNCTION get_daily_missions(p_perfil_id int, limit_count int DEFAULT 3)
RETURNS SETOF mision AS $$
DECLARE
    v_conteo int;
BEGIN
    -- 1. Contar cuántas misiones tiene asignadas el usuario HOY
    SELECT COUNT(*) INTO v_conteo 
    FROM progreso_usuario 
    WHERE perfil_id = p_perfil_id AND fecha = CURRENT_DATE;

    -- 2. Si no tiene misiones asignadas hoy, elegimos 3 al azar y las congelamos
    IF v_conteo = 0 THEN
        INSERT INTO progreso_usuario (perfil_id, mision_id, completado, fecha)
        SELECT p_perfil_id, id, false, CURRENT_DATE
        FROM mision
        ORDER BY random()
        LIMIT limit_count;
    END IF;

    -- 3. Devolver las misiones que quedaron asociadas al usuario para el día de hoy
    RETURN QUERY 
    SELECT m.* FROM mision m
    JOIN progreso_usuario p ON p.mision_id = m.id
    WHERE p.perfil_id = p_perfil_id AND p.fecha = CURRENT_DATE;
END;
$$ LANGUAGE plpgsql;

-----------------------------------------
-- 6. SEEDERS (Datos Iniciales Nuevos)
-----------------------------------------

-- 1. Perfil de prueba (id = 1)
INSERT INTO perfil (id, nombre, email, contrasena, f_nac) 
VALUES (1, 'JorgeKirko47', 'jorge@example.com', '123456', '1995-05-15');

-- 2. Cartas de prueba (Nuevas cartas añadidas)
INSERT INTO carta (id, nombre_carta, categoria, borde, imagen, centro, normal_map, texto, propietario) VALUES 
(1, 'Kirko Básico', 'Comun', 'default', 'pokmeon.png', 'buffkirk.jpeg', 'paper1.jpg', 'La forma básica y trabajadora de Kirko.', 1),
(2, 'Bob Esponja', 'Comun', 'default', 'pokmeon.png', 'bob.jpg', 'paper1.jpg', '¿Quién vive en la piña debajo del mar?', 1),
(3, 'Guerrero Común', 'Comun', 'silver', 'pokmeon.png', '6_1x1.jpg', 'paper1.jpg', 'Un guerrero listo para cualquier combate básico.', NULL),
(4, 'Campeón Raro', 'Raro', 'silver', 'pokmeon.png', '7_1x1.jpg', 'paper1.jpg', 'Habilidades afinadas y listas para la batalla.', NULL),
(5, 'Místico Épico', 'Epico', 'gold', 'pokmeon.png', '8_1x1.jpg', 'paper1.jpg', 'Una presencia majestuosa de poder inconmensurable.', NULL),
(6, 'Ancestral Legendario', 'Legendario', 'diamond', 'pokmeon.png', '9_1x1.jpg', 'paper1.jpg', 'Una fuerza cósmica que trasciende el tiempo.', NULL),
(7, 'Artefacto Dorado', 'Legendario', 'diamond', 'pokmeon.png', 'image3.png', 'paper1.jpg', 'Un objeto legendario envuelto en misterio.', NULL);

-- 3. Misiones verificables (30 misiones)
INSERT INTO mision (id, tipo, nombre, descripcion, recompensa) VALUES 
(1, 'Fácil', 'Caminar 2,000 pasos', 'Usa tu podómetro para registrar 2,000 pasos hoy.', 'Comun'),
(2, 'Media', 'Caminar 5,000 pasos', 'Llega a 5,000 pasos verificados por la app.', 'Raro'),
(3, 'Difícil', 'Caminar 10,000 pasos', 'Alcanza la meta de 10,000 pasos diarios.', 'Epico'),
(4, 'Fácil', 'Tomar una foto al aire libre', 'Usa la cámara para capturar una foto con mucha luz natural.', 'Comun'),
(5, 'Media', 'Leer un texto en voz alta', 'Usa el micrófono y lee el texto mostrado en pantalla sin errores.', 'Raro'),
(6, 'Fácil', 'Diario de 50 palabras', 'Escribe cómo te sientes usando el teclado (mínimo 50 palabras).', 'Comun'),
(7, 'Difícil', 'Visitar un parque', 'La app verificará mediante GPS que te encuentras en un área verde.', 'Epico'),
(8, 'Media', 'Agitar el teléfono', 'Agita el teléfono 50 veces seguidas. Usa tu giroscopio.', 'Raro'),
(9, 'Fácil', 'Trivia rápida', 'Responde 3 preguntas de conocimiento general en menos de 1 minuto.', 'Comun'),
(10, 'Media', 'Desconexión boca abajo', 'Mantén el teléfono boca abajo sobre la mesa durante 30 minutos.', 'Raro'),
(11, 'Difícil', 'Completar el puzzle', 'Resuelve el rompecabezas en pantalla en menos de 2 minutos.', 'Epico'),
(12, 'Fácil', 'Cantar por 10s', 'Graba un audio cantando o tarareando una canción por 10 segundos.', 'Comun'),
(13, 'Media', 'Caza de colores', 'Usa la cámara y apunta hacia algo de color azul brillante.', 'Raro'),
(14, 'Difícil', 'Correr 2 km', 'Corre 2 kilómetros seguidos usando el podómetro y GPS para verificar velocidad.', 'Epico'),
(15, 'Fácil', 'Escanear un QR', 'Encuentra y escanea un código QR usando tu cámara.', 'Comun'),
(16, 'Media', 'Subir 3 pisos', 'Sube 3 pisos por escalera. Se verificará con el barómetro/altímetro.', 'Raro'),
(17, 'Fácil', 'Dibujo en pantalla', 'Traza el patrón solicitado sin levantar el dedo.', 'Comun'),
(18, 'Difícil', 'Estatua por 5 mins', 'Quédate en un lugar sin mover el celular ni caminar por 5 minutos.', 'Epico'),
(19, 'Extrema', 'Club de las 5 AM', 'Abre la app a las 5:00 AM exactas.', 'Legendario'),
(20, 'Fácil', 'Día de lluvia', 'Graba 10 segundos del sonido de la lluvia (se usa micrófono).', 'Comun'),
(21, 'Media', 'Resistencia dactilar', 'Mantén presionado el botón central de la pantalla durante 60 segundos.', 'Raro'),
(22, 'Difícil', 'Rotación 360', 'Da 10 vueltas sobre ti mismo. El giroscopio contará las rotaciones.', 'Epico'),
(23, 'Media', 'Caminata rápida', 'Camina a una velocidad de al menos 5 km/h durante 10 minutos.', 'Raro'),
(24, 'Fácil', 'Encender linterna', 'Mantén la linterna encendida desde la app por 1 minuto.', 'Comun'),
(25, 'Media', 'Reconocimiento facial', 'Sonríe a la cámara frontal hasta que la IA lo detecte.', 'Raro'),
(26, 'Difícil', 'Prueba matemática', 'Resuelve 5 ecuaciones matemáticas en menos de 30 segundos.', 'Epico'),
(27, 'Extrema', 'Velocidad de tipeo', 'Toca la pantalla 100 veces en solo 10 segundos.', 'Legendario'),
(28, 'Difícil', 'Llegar al gimnasio', 'Ve a un gimnasio cercano (verificación por GPS).', 'Epico'),
(29, 'Media', 'Abecedario inverso', 'Escribe Z, Y, X... hasta la A en menos de 20s en el teclado.', 'Raro'),
(30, 'Extrema', 'Maratón de pasos', 'Da 20,000 pasos en un solo día.', 'Legendario');

-----------------------------------------
-- 7. REINICIO DE SECUENCIAS
-----------------------------------------
SELECT setval('perfil_id_seq', (SELECT MAX(id) FROM perfil));
SELECT setval('mision_id_seq', (SELECT MAX(id) FROM mision));

-----------------------------------------
-- 8. RECARGAR CACHÉ DE SUPABASE API
-----------------------------------------
-- Esto fuerza a PostgREST a recargar el esquema para que la app pueda ver las nuevas tablas
NOTIFY pgrst, 'reload schema';